Madhav Pull request
IT-Club-Pulchowk/Git-Workshop pull request #37
Opened 2021-05-17 12:30 UTC by BCT-Madhav

I hope I had completed as stated in case of any error contact through mail at 077bct041.madhav@pcampus.edu.np

2021-05-17 17:08 UTC, ABoredComputerEngineer requested changes
Looks like you made a typo in  your email address. Could you please look into that?

2021-05-18 07:45 UTC, BCT-Madhav commented
Bujina ni daju maile

On Mon, May 17, 2021, 10:53 PM Asim Maharjan ***@***.***>
wrote:

> *@ABoredComputerEngineer* requested changes on this pull request.
>
> Looks like you made a typo in your email address. Could you please look
> into that?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IT-Club-Pulchowk/Git-Workshop/pull/37#pullrequestreview-661208668>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT6BZE53E5DTUGORRKMOOK3TOFERZANCNFSM45ALTL6A>
> .
>

2021-05-18 10:34 UTC, BCT-Madhav commented
I have corrected the error in the email address. Thank you for the response. If any further error are left please inform me.
Thank You 
Madhav Prasad Parajuli
[BCT-Madhav.txt](https://github.com/IT-Club-Pulchowk/Git-Workshop/files/6500600/BCT-Madhav.txt)

2021-05-18 11:08 UTC, ABoredComputerEngineer commented on Stories/BCT-Madhav.txt
> +email: 077bct41.madhav@pcampus.edu.np
This should be `077bct041.madhva@pcampus.edu.np`.

2021-05-18 11:08 UTC, ABoredComputerEngineer requested changes
Please check your email again. Looks like you missed a '0'.

2021-05-18 11:14 UTC, BCT-Madhav commented
Sorry for the last error it is solved now 
[BCT-Madhav.txt](https://github.com/IT-Club-Pulchowk/Git-Workshop/files/6500818/BCT-Madhav.txt)

2021-05-18 11:15 UTC, merged

2021-05-18 11:15 UTC, ABoredComputerEngineer commented
Thank you for your submission! Have a nice day!