Assignment Submission
IT-Club-Pulchowk/Git-Workshop pull request #38
Opened 2021-05-17 13:34 UTC by niyoj

2021-05-17 17:12 UTC, ABoredComputerEngineer requested changes
Please change the filename to your Github username.

2021-05-17 17:31 UTC, niyoj commented
The file has been renamed

2021-05-18 11:06 UTC, merged

2021-05-18 11:06 UTC, ABoredComputerEngineer commented
Thank you for your submission!

2021-05-26 03:58 UTC, niyoj commented
When will we receive the certificate of participation?


On Tue, May 18, 2021 at 4:52 PM Asim Maharjan ***@***.***>
wrote:

> Thank you for your submission!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IT-Club-Pulchowk/Git-Workshop/pull/38#issuecomment-843076739>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUBLKYXZE7LFAZJXK5535LLTOJC6HANCNFSM45APFJVQ>
> .
>